site_name: Rahmet MINIAPP
pages:
- Главная: 'index.md'
- Бесшовная авторизация: 'auth.md'
- Оплата: 'pay.md'
- Реферальная программа: 'referralprogram.md'
- Haptic Touch: 'haptic.md'
theme: readthedocs